apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "overpass-api.fullname" . }}
  labels:
    {{- include "overpass-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiService.replicaCount }}
  selector:
    matchLabels:
      {{- include "overpass-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "overpass-api.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "overpass-api.fullname" . }}-sa
      initContainers:
      - name: overpass-init
        image: "{{ .Values.updateJob.image.repository }}:{{ .Values.updateJob.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.updateJob.image.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - |
          set -ex
          if [ -z "$(ls -A /app/db)" ]; then
            echo "Volume is empty, initializing..."
            OVERPASS_MODE=update /app/update_overpass.sh
          else
            echo "Volume already initialized"
          fi
        env:
        - name: OVERPASS_META
          value: {{ .Values.overpassMeta | quote }}
        - name: OVERPASS_PLANET_URL
          value: {{ .Values.updateJob.planetUrl | quote }}
        - name: OVERPASS_DIFF_URL
          value: {{ .Values.updateJob.diffUrl | quote }}
        - name: OVERPASS_UPDATE_FREQUENCY
          value: {{ .Values.updateJob.updateFrequency | quote }}
        - name: OVERPASS_COMPRESSION
          value: {{ .Values.overpassCompression | quote }}
        - name: OVERPASS_RULES_LOAD
          value: {{ .Values.updateJob.rulesLoad | quote }}
        volumeMounts:
        - name: data
          mountPath: /app/db
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.apiService.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiService.image.pullPolicy }}
          env:
          - name: OVERPASS_MODE
            value: "readonly"
          - name: OVERPASS_META
            value: {{ .Values.overpassMeta | quote }}
          - name: OVERPASS_FASTCGI_PROCESSES
            value: {{ .Values.apiService.fastcgiProcesses | quote }}
          - name: OVERPASS_RATE_LIMIT
            value: {{ .Values.apiService.rateLimit | quote }}
          - name: OVERPASS_TIME
            value: {{ .Values.apiService.time | quote }}
          - name: OVERPASS_SPACE
            value: {{ .Values.apiService.space | quote }}
          - name: OVERPASS_MAX_TIMEOUT
            value: {{ .Values.apiService.maxTimeout | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: data
            mountPath: /app/db
            readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "overpass-api.fullname" . }}-data
